name: Thomas
favicon: null
layout_spectrum: 0.93268
typography_spectrum: 0.5727140982635319
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.19400554383173585
  lightness: 0.12614920502528548
  saturation: 0.0908900829963386
  rhythmicContrast: 0.7100397127214819
purpose: []
